// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailcarTrips.Server.Data;

#nullable disable

namespace RailcarTrips.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210231547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vancouver",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Victoria",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kelowna",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kamloops",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Prince George",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Calgary",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Edmonton",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lethbridge",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Red Deer",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fort McMurray",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Regina",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Saskatoon",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Moose Jaw",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Brandon",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Winnipeg",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Thunder Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sault Ste. Marie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sudbury",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            Name = "North Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barrie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Toronto",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Mississauga",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Hamilton",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            Name = "London",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kitchener",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Windsor",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            Name = "St. Catharines",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Oshawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Kingston",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ottawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Gatineau",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Montreal",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Quebec City",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Sherbrooke",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Trois-Rivières",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Saguenay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Rimouski",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Edmundston",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Fredericton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Moncton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Saint John",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Bathurst",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Charlottetown",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Summerside",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Sydney",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Truro",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            Name = "New Glasgow",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dartmouth",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Halifax",
                            TimeZone = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.EquipmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("TripId");

                    b.ToTable("EquipmentEvents");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.EventCodeDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("EventCodeDefinitions");

                    b.HasData(
                        new
                        {
                            Code = "W",
                            Description = "Released",
                            LongDescription = "Railcar equipment is released from origin"
                        },
                        new
                        {
                            Code = "A",
                            Description = "Arrived",
                            LongDescription = "Railcar equipment arrives at a city on route"
                        },
                        new
                        {
                            Code = "D",
                            Description = "Departed",
                            LongDescription = "Railcar equipment departs from a city on route"
                        },
                        new
                        {
                            Code = "Z",
                            Description = "Placed",
                            LongDescription = "Railcar equipment is placed at destination"
                        });
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalTripHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.EquipmentEvent", b =>
                {
                    b.HasOne("RailcarTrips.Server.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Server.Data.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Trip", b =>
                {
                    b.HasOne("RailcarTrips.Server.Data.Entities.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Server.Data.Entities.City", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
